### ISSUE TITLE
Update layer.js to example quality

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/geoApi#13]
Update `layer.js` with appropriate structure, sample functions, and comments

We need an example of "how things should look" that other contributors can reference. Right now `layer.js` is about as barebones as it can get.  Please make it look like how you want files to look, as it will be referenced as a starting point / example in other tasks.

**Comment by alyec** [comment]
Added a commented version of the proj module to https://github.com/fgpv-vpgf/geoApi/wiki/How-to-Add-a-New-Section-to-geoApi .  Leaving layer as is for now.
