### ISSUE TITLE
Need ability to access ESRI dojo map events for viewer API

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/geoApi#275]
ArcGIS API's [working with events](https://developers.arcgis.com/javascript/3/jshelp/inside_events.html) demos indicate (near the bottom of the page) that an ESRI event can be stopped.

```js
event.stop(event);
```

When binding API events on the viewer, it would be nice to bind them directly to the ESRI event. This allows us to make certain map events `stoppable` via the API (such as an extension which stops an identify click and instead opens a pop-up with info/data).

We could:

1. Add a function to https://github.com/fgpv-vpgf/geoApi/blob/master/src/events.js which is similar to `wrapEvents` but only takes one event at a time and returns the dojo/esri event object. Something like  `function esriOn(mapInstance, eventName, fireCallback);` 
2. Correct the current `on` function in map instances so it points to the esri/dojo `on` function (this goes against our keeping dojo out of the core though).

Though ESRI's documentation can be flaky sometimes, the method name may have changed or just plain doesn't stop the event. Some testing would be needed.

**Comment by james-rae** [comment]
I believe we can do this already.  Example code:

```js
// standard startup wires up default handlers
const wrapResult = gapi.events.wrapEvents(mapInstanceObject, {          
            'extent-change': data => {
                console.log('my extent changed:', data);
            },
            click: clickEvent => {
                console.log('I done did a click:', clickEvent);
            }
      });

// time passes.  someone want's to stop current click event handler from triggering
wrapResult['click'].remove();
```

So in this situation, the underlying ESRI click event is still firing, but our handler is no longer reacting to it.  So if we wanted to add a new handler, we could do so. I believe this would do what you want in your identify example (correct me if I'm wrong).

In the above sample, `wrapResult['click']` is a DOJO object, `remove()` being a DOJO method of it.  If we want to be extra careful, we could technically change geoApi to wrap the DOJO object into a "neutral" object that also has method `remove()`, which internally calls the DOJO object.remove inside.  This would let us keep the interface if we went to something that is not DOJO; might be overkill wrapping at the moment. Am curious to here opinions.

**Comment by milesap** [comment]
Current solution works well for current API needs
